image: docker:latest

variables:
  REPO: sample-node-ayeaye
  GITLAB_REGISTRY_URL: registry.gitlab.com/ttrahan
  DOCKER_HUB_URL: ttrahan
  IMAGE_TAG: $CI_BUILD_REF_NAME.$CI_BUILD_ID
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stages:
  - build
  - deploy

buildImage:
  stage: build
  script:
    - "echo ref_name: $CI_BUILD_REF_NAME"
    - echo $CI_BUILD_ID
    - echo $IMAGE_TAG
    # - docker build -t $GITLAB_REGISTRY_URL/$REPO:$IMAGE_TAG .
    # - docker push $DOCKER_HUB_URL/$REPO:$IMAGE_TAG
    # - docker push $GITLAB_REGISTRY_URL/$REPO:$IMAGE_TAG

# deployToTestCluster:
#   stage: deploy
#   environment: test
#   script:
#     -
