image: docker:latest

variables:
  REPO: kube-example
  DOCKER_REGISTRY_URL: registry.gitlab.com/ttrahan
  GIT_TAG: $CI_BUILD_TAG
  IMAGE_TAG: $CI_BUILD_REF_NAME.$CI_BUILD_ID
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stages:
  - build
  - deployDev
  - release
  - deployTest

buildImage:
  stage: build
  script:
    - if [[ $CI_BUILD_TAG ]]; then
      IMAGE="$DOCKER_REGISTRY_URL/$REPO:$GIT_TAG" &&
      echo "Building $IMAGE" &&
      docker build --pull -t $IMAGE .;
      else
        IMAGE="$DOCKER_REGISTRY_URL/$REPO:$IMAGE_TAG" &&
        echo "Building $IMAGE" &&
        docker build --pull -t $IMAGE .;
      fi
    - docker push $IMAGE

deployToDev:
  stage: deployDev
  environment: dev
  script:
    - docker version

genRelease:
  stage: release
  environment: dev
  script:
    - IMAGE="$DOCKER_REGISTRY_URL/$REPO:$GIT_TAG"
    - docker pull $IMAGE
    - docker tag $IMAGE $IMAGE-release
    - docker push $IMAGE-release
  only:
    - tags

deployToTest:
  stage: deployTest
  environment: test
  script:
    - docker version
  when: manual
  only:
    - tags
