image: docker:latest

variables:
  REPO: kube-example
  DOCKER_REGISTRY_URL: registry.gitlab.com/ttrahan
  IMAGE_TAG: $CI_BUILD_REF_NAME.$CI_BUILD_ID
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stages:
  - build
  - deployDev
  - release
  - deployTest

buildImage:
  stage: build
  script:
    - docker images
    - docker build --pull -t $DOCKER_REGISTRY_URL/$REPO:$IMAGE_TAG .
    - docker push $DOCKER_REGISTRY_URL/$REPO:$IMAGE_TAG

deployToDev:
  stage: deployDev
  environment: dev
  script:
    - docker version

genRelease:
  stage: release
  environment: dev
  script:
    - docker pull $DOCKER_REGISTRY_URL/$REPO:$IMAGE_TAG
    - docker tag $DOCKER_REGISTRY_URL/$REPO:$IMAGE_TAG
  only:
    - tags

deployToTest:
  stage: deployTest
  environment: test
  script:
    - docker version
  when: manual
