image: docker:latest

variables:
  REPO: sample-node-ayeaye
  DOCKER_REGISTRY_URL: registry.gitlab.com/ttrahan
  IMAGE_TAG: $CI_BUILD_REF_NAME.$CI_BUILD_ID
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stages:
  - build
  - deploy

buildImage:
  stage: build
  script:
    - docker images
    - docker build -t $DOCKER_REGISTRY_URL/$REPO:$IMAGE_TAG .
    - docker push $DOCKER_REGISTRY_URL/$REPO:$IMAGE_TAG

# deployToTestCluster:
#   stage: deploy
#   environment: test
#   script:
#     -
