jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline job
# TEST deployment to Kube cluster on AWS
  - name: kube-helm-deploy-test-sample
    type: runSh
    steps:
      - IN: int-aws
      - IN: int-kube
      - IN: params-test-kube-helm
      - IN: repo-sample-kube-helm
        switch: off
      - IN: img-sample-kube-helm
      - IN: params-sample-test-kube-helm
      - IN: img-nginx
      - TASK:
        - script: printenv | grep "IMGOPTS" 
        - script: . $REPOSAMPLEKUBEHELM_PATH/gitRepo/pipeline/prepEnvironment.sh
        - script: . $REPOSAMPLEKUBEHELM_PATH/gitRepo/pipeline/deploy.sh

# add pipeline job
# PROD deployment to Kube cluster on AWS
  - name: kube-helm-deploy-prod-sample
    type: runSh
    steps:
      - IN: kube-helm-deploy-test-sample
        switch: off
      - IN: int-aws
      - IN: int-kube
      - IN: params-kube-helm-prod
      - IN: repo-sample-kube-helm
        switch: off
      - IN: params-sample-kube-helm-prod
      - TASK:
        - script: . $REPOSAMPLEKUBEHELM_PATH/gitRepo/pipeline/prepEnvironment.sh
        - script: . $REPOSAMPLEKUBEHELM_PATH/gitRepo/pipeline/deploy.sh
