jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline workflow

# TEST deployment to Kube cluster on AWS
  - name: kube-deploy-test-sample
    type: runSh
    steps:
      - IN: img-sample-kube
      - IN: img-opts-sample-kube
      - IN: params-global-kube
      - IN: params-sample-test-kube
      - IN: int-aws
      - TASK:
        - script: ./pipeline/install.sh
        - script: ./pipeline/deploy.sh
