jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline workflow
# TEST deployment to Kube cluster on AWS
  - name: kube-deploy-test-sample
    type: runSh
    steps:
      - IN: repo-sample-kube
        switch: off
      - IN: params-sample-test-kube
      - IN: int-aws
      - IN: img-sample-kube
      - IN: img-opts-sample-kube
      - TASK:
        - script: . /build/IN/repo-sample-kube/gitRepo/pipeline/prepEnvironment.sh kube-deploy-test-sample repo-sample-kube params-sample-test-kube int-aws img-sample-kube img-opts-sample-kube
        # - script: . /build/IN/repo-sample-kube/gitRepo/pipeline/deploy.sh
