jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline job
# TEST deployment to Kube cluster on AWS
  - name: kube-deploy-test-sample
    type: runSh
    steps:
      - IN: params-test-kube
      - IN: params-sample-test-kube
      - IN: repo-sample-kube
        switch: off
      - IN: int-aws
      - IN: int-kube
      - IN: img-sample-kube
      - IN: img-nginx
      - IN: img-opts-sample-kube-test
      - TASK:
        - script: . $REPOSAMPLEKUBE_PATH/gitRepo/pipeline/prepEnvironment.sh
        - script: . $REPOSAMPLEKUBE_PATH/gitRepo/pipeline/deploy.sh

# add pipeline job
# PROD deployment to Kube cluster on AWS
  - name: kube-deploy-prod-sample
    type: runSh
    steps:
      - IN: kube-deploy-test-sample
        switch: off
      - IN: params-prod-kube
      - IN: int-aws
      - IN: img-opts-sample-kube-prod
      - TASK:
        - script: . /build/IN/repo-sample-kube/gitRepo/pipeline/prepEnvironment.sh
        - script: . /build/IN/repo-sample-kube/gitRepo/pipeline/deploy.sh
