jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline workflow
# TEST deployment to Kube cluster on AWS
  - name: kube-deploy-test-sample
    type: runSh
    steps:
      - IN: params-test-kube
      - IN: params-sample-test-kube
      - IN: repo-sample-kube
        switch: off
      - IN: int-aws
      - IN: int-kube
      - IN: img-sample-kube
      - IN: img-nginx
      - IN: img-opts-sample-kube-test
      - TASK:
        - script: mkdir -p ~/.kube && echo "$INTKUBE_INTEGRATION_MASTERKUBECONFIGCONTENT" > ~/.kube/config
        - script: . $REPOSAMPLEKUBE_PATH/gitRepo/pipeline/prepEnvironment.sh
        - script: aws s3 cp ~/.kube/config s3://clusters.example-kube-cluster.com/test_config
        - script: kubectl get pods
        - script: . $REPOSAMPLEKUBE_PATH/gitRepo/pipeline/deploy.sh

# add pipeline workflow
# PROD deployment to Kube cluster on AWS
  - name: kube-deploy-prod-sample
    type: runSh
    steps:
      - IN: kube-deploy-test-sample
        switch: off
      - IN: params-prod-kube
      - IN: int-aws
      - IN: img-opts-sample-kube-prod
      - TASK:
        - script: . /build/IN/repo-sample-kube/gitRepo/pipeline/prepEnvironmentProd.sh
        - script: . /build/IN/repo-sample-kube/gitRepo/pipeline/deploy.sh
