jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline workflow

# TEST deployment to Kube cluster on AWS
  - name: kube-deploy-test-sample
    type: runSh
    steps:
      - IN: int-aws
      - IN: img-sample-kube
      - IN: repo-sample-kube
      - IN: img-opts-sample-kube
      - IN: params-sample-test-kube
      - TASK:
        - script: ./build/IN/repo-sample-kube/gitRepo/pipeline/prepEnvironment.sh repo-sample-kube params-sample-test-kube int-aws
        - script: ./build/IN/repo-sample-kube/gitRepo/pipeline/deploy.sh
