apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: sample-node-ayeaye-test
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  # Keep record of 10 revisions for rollback
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: sample-node-ayeaye
        env: test
    spec:
      containers:
      - name: sample-node-ayeaye
        image: kube-example:master.3
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "test"
        - name: PORT
          value: "80"
        resources:
          requests:
            memory: 64
            cpu: 0.25
