apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: sample-node-ayeaye
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  # Keep record of 10 revisions for rollback
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: sample-node-ayeaye
        env: dev
    spec:
      containers:
      - name: sample-node-ayeaye
        image: /:
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: ""
        - name: PORT
          value: ""
        resources:
          requests:
            memory: 
            cpu: 
      imagePullSecrets:
      - name: gitlab-ttrahan
