# Default values for chartSample.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: test

sample:
  replicaCount: 1
  image:
    repo: ttrahan/sample_node_ayeaye
    tag: master.3
  resources:
    limits:
      cpu: .25
      memory: 128
  port: 80

nginx:
  image:
    repo: nginx
    tag: 1.7.9

