apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: nginx-$ENVIRONMENT
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  # Keep record of 10 revisions for rollback
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nginx
        env: $ENVIRONMENT
    spec:
      containers:
      - name: nginx
        image: $NGINX_IMAGE_URL:$NGINX_IMAGE_TAG
        ports:
        - containerPort: 80
