apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: sample-node-ayeaye-$ENVIRONMENT
spec:
  # 3 Pods should exist at all times.
  replicas: $SAMPLE_REPLICAS
  # Keep record of 10 revisions for rollback
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: sample-node-ayeaye
        env: $ENVIRONMENT
    spec:
      containers:
      - name: sample-node-ayeaye
        image: $SAMPLE_IMAGE_URL:$SAMPLE_IMAGE_TAG
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "$ENVIRONMENT"
        - name: PORT
          value: "$SAMPLE_PORT"
        resources:
          requests:
            memory: $SAMPLE_MEMORY
            cpu: $SAMPLE_CPU
