apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: sample-node-ayeaye
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  # Keep record of 10 revisions for rollback
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: sample-node-ayeaye
    spec:
      containers:
      - name: sample-node-ayeaye
        image: $DOCKER_REGISTRY_URL/sample_node_ayeaye:$TAG
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "$ENVIRONMENT"
        - name: PORT
          value: "$PORT"
        resources:
          requests:
            memory: $IMGOPTSSAMPLE_VERSION_MEMORY
            cpu: $IMGOPTSSAMPLE_VERSION_CPUSHARES
